#!/usr/bin/env bash

#weather=$(for x in 1; do echo "$(curl -Ss 'https://wttr.in/trivandrum' | cut -d ' ' -f 3 | head -1 | xargs echo)  $(curl -Ss 'https://wttr.in/trivandrum?0&T&Q' | cut -c 16- | head -3 | xargs echo)"; done;)
 weather=$(curl -Ss 'https://wttr.in/trivandrum?0&T&Q' | cut -c 16- | head -2 | xargs echo)
span1="<span background='#003b4a'>" #021215
span2=" </span>"
#weather=" some temp "
fulltext="$span1$weather$span2"
echo "$fulltext"
#echo $weather
# echo "#FF0220"
